export const
  UPDATE_CHARACTERS = "UPDATE_CHARACTERS",
  SHOW_MODAL        = "SHOW_MODAL",
  HIDE_MODAL        = "HIDE_MODAL",
  READ_MESSAGES     = "READ_MESSAGES",
  SET_MESSAGE       = "SET_MESSAGE",
  SET_PAGE_SIZE     = "SET_PAGE_SIZE";
